export const navBarLinksNames = {
  MURMANSK_NEWS: "MURMANSK_NEWS",
  FOREIGN_OVERVIEW: "FOREIGN_OVERVIEW",
  FRENCH_SPIDER_MAN: "FRENCH_SPIDER_MAN",
  GALERY: "GALERY",
  VIDEO_STORE: "VIDEO_STORE"
};
